# Generated by Django 3.2.6 on 2021-08-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BiliUser',
            fields=[
                ('mid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('sex', models.TextField()),
                ('level', models.IntegerField()),
                ('sign', models.TextField()),
                ('vip', models.TextField()),
                ('fans_medal', models.TextField()),
                ('following', models.IntegerField()),
                ('follower', models.IntegerField()),
            ],
        ),
    ]
